### ISSUE TITLE
SqlCeDbCacheTests.InsertFindRemoveTest is failing

### ISSUE THREAD

**Issue by pauldendulk** [BruTile/BruTile#22]
Perhaps SqlCeDbCache should be removed altogether.

**Comment by FObermaier** [comment]
The test is not failing on my machine. What kind of error/failure do you get?

**Comment by pauldendulk** [comment]
System.IndexOutOfRangeException : An SqlCeParameter with ParameterName '@level' is not contained by this SqlCeParameterCollection.
   at System.Data.SqlServerCe.SqlCeCommand.CompileQueryPlan()
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(CommandBehavior behavior, String method, ResultSetOptions options)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteNonQuery()
   at BruTile.Cache.DbCache`1.Add(TileIndex index, Byte[] image) in DbCache.cs: line 276
   at BruTile.Tests.Cache.SqlCeDbCacheTests.InsertTiles() in SqlCeDbCacheTests.cs: line 51
   at BruTile.Tests.Cache.CacheTests`1.TestInsertFindRemove() in CacheTests.cs: line 29
   at BruTile.Tests.Cache.SqlCeDbCacheTests.InsertFindRemoveTest() in SqlCeDbCacheTests.cs: line 134

**Comment by pauldendulk** [comment]
It is v2.0.50727 of System.Data.SqlServerCe located at C:\WINDOWS\assembly\GAC_MSIL\System.Data.SqlServerCe\9.0.242.0__89845dcd8080cc91\System.Data.SqlServerCe.dll

**Comment by pauldendulk** [comment]
Which test runner do you use? I use resharper which caused a fail on another test related to x86 vs x64

**Comment by pauldendulk** [comment]
Test is green with my current setup. Let's assume it was a ReSharper problem.

**Comment by pauldendulk** [comment]
Test is green with my current setup. Let's assume it was a ReSharper problem.

**Comment by pauldendulk** [comment]
Test is green with my current setup. Let's assume it was a ReSharper problem.
